version: "2.4"

services:
  deletron3030:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-deletron3030-test.rule=Host(`deletron3030.devtest.vanhack.ca`)"
      - "traefik.http.routers.vanhack-deletron3030-test.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-deletron3030-test.tls=true"
      - "traefik.http.routers.vanhack-deletron3030-test.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
