
services:
  deletron3030:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-deletron3030-prod.rule=Host(`deletron3030.vanhack.ca`)"
      - "traefik.http.routers.vanhack-deletron3030-prod.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-deletron3030-prod.tls=true"
      - "traefik.http.routers.vanhack-deletron3030-prod.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
