version: "2.4"

services:
  redirect:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-redirect-test.rule=(Host(`slack.devtest.vanhack.ca`) || Host(`vancouver.devtest.vanhack.ca`))"
      - "traefik.http.routers.vanhack-redirect-test.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-redirect-test.tls=true"
      - "traefik.http.routers.vanhack-redirect-test.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
