version: "3.3"

services:
  redirect:
    container_name: redirect
    image: nginx
    network_mode: bridge
    restart: always
    volumes:
    - ./services/redirect/conf.d:/etc/nginx/conf.d/
    environment:
      VIRTUAL_HOST: "*.vanhack.ca,*.vanhack.space"
      LETSENCRYPT_HOST: "*.vanhack.ca,*.vanhack.space"
