
services:
  redirect:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-redirect-prod.rule=(Host(`slack.vanhack.ca`) || Host(`slack.vanhack.space`) || Host(`vancouver.vanhack.ca`))"
      - "traefik.http.routers.vanhack-redirect-prod.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-redirect-prod.tls=true"
      - "traefik.http.routers.vanhack-redirect-prod.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
