services:
    grafana:
        network_mode: bridge
        links:
            - influxdb:influxdb
        environment:
            VIRTUAL_HOST: stats.vanhack.ca
            LETSENCRYPT_HOST: stats.vanhack.ca
