
services:
  grafana:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-grafana-prod.rule=Host(`stats.vanhack.ca`)"
      - "traefik.http.routers.vanhack-grafana-prod.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-grafana-prod.tls=true"
      - "traefik.http.routers.vanhack-grafana-prod.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
