version: '2.4'

services:
  urlredirector:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-urlredirector-prod.rule=Host(`r.vanhack.ca`)"
      - "traefik.http.routers.vanhack-urlredirector-prod.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-urlredirector-prod.tls=true"
      - "traefik.http.routers.vanhack-urlredirector-prod.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
