version: '2.4'

services:
  urlredirector:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-urlredirector-test.rule=Host(`r.devtest.vanhack.ca`)"
      - "traefik.http.routers.vanhack-urlredirector-test.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-urlredirector-test.tls=true"
      - "traefik.http.routers.vanhack-urlredirector-test.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
