version: '2.4'

services:
  urlredirector:
    container_name: urlredirector
    image: vanhack/redirect
    network_mode: bridge
    restart: always
    volumes:
    - ./services/urlredirector/config.json:/app/config.json
    environment:
      VIRTUAL_HOST: r.vanhack.ca
      LETSENCRYPT_HOST: r.vanhack.ca
