
services:
  wiki-redirector:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-wiki-redirector-test.rule=Host(`wiki.devtest.vanhack.ca`)"
      - "traefik.http.routers.vanhack-wiki-redirector-test.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-wiki-redirector-test.tls=true"
      - "traefik.http.routers.vanhack-wiki-redirector-test.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
