
services:
  itlb:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-itlb-prod.rule=(Host(`itlb.vanhack.ca`) || Host(`isthelaserbusy.vanhack.ca`))"
      - "traefik.http.routers.vanhack-itlb-prod.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-itlb-prod.tls=true"
      - "traefik.http.routers.vanhack-itlb-prod.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
