
services:
  itlb:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vanhack-itlb-test.rule=(Host(`itlb.devtest.vanhack.ca`) || Host(`isthelaserbusy.devtest.vanhack.ca`))"
      - "traefik.http.routers.vanhack-itlb-test.entryPoints=web,websecure"
      - "traefik.http.routers.vanhack-itlb-test.tls=true"
      - "traefik.http.routers.vanhack-itlb-test.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=proxy"
