version: "3.3"
services:
  itlb:
    container_name: itlb
    image: vanhack/itlb
    entrypoint: ["bin/www"]
    network_mode: bridge
    restart: always
    environment:
      VIRTUAL_HOST: itlb.vanhack.ca,isthelaserbusy.com,www.isthelaserbusy.com
      LETSENCRYPT_HOST: itlb.vanhack.ca,isthelaserbusy.com,www.isthelaserbusy.com
