version: "3.3"
services:
  nginx-proxy-letsencrypt:
    container_name: nginx_proxy_letsencrypt
    depends_on:
    - nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    network_mode: bridge
    restart: always
    volumes:
    - ./core/nginx/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
    - service:nginx-proxy:rw
