services:
    TEMPLATE:
        networks:
            - proxy
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.vanhack-TEMPLATE-prod.rule=Host(`TEMPLATE.vanhack.ca`)'
            - 'traefik.http.routers.vanhack-TEMPLATE-prod.entryPoints=web,websecure'
            - 'traefik.http.routers.vanhack-TEMPLATE-prod.tls=true'
            - 'traefik.http.routers.vanhack-TEMPLATE-prod.tls.certresolver=lets-encrypt'
            - 'traefik.docker.network=proxy'
