version: "2.4"

services:
  isvhsopen:
    image: vanhack/isvhsopen:latest
    container_name: isvhsopen
    restart: always
    links:
      - influxdb:influxdb
    depends_on:
      - influxdb
    env_file:
      - ./env/_influxdb
      - ./env/_slack
