services:
    isvhsopen:
        networks:
            - proxy
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.vanhack-isvhsopen-test.rule=(Host(`isvhsopen.devtest.vanhack.ca`) || Host(`door.devtest.vanhack.ca`))'
            - 'traefik.http.routers.vanhack-isvhsopen-test.entryPoints=web,websecure'
            - 'traefik.http.routers.vanhack-isvhsopen-test.tls=true'
            - 'traefik.http.routers.vanhack-isvhsopen-test.tls.certresolver=lets-encrypt'
            - 'traefik.docker.network=proxy'
