version: "3.3"
services:
  portal:
    container_name: portal
    image: vanhack/vhs-portal
    entrypoint: ["bin/www"]
    network_mode: bridge
    restart: always
    environment:
      VIRTUAL_HOST: portal.vanhack.ca
      LETSENCRYPT_HOST: portal.vanhack.ca
      DEBUG: "*"
    volumes:
    - ./services/portal/config.json:/usr/src/app/config.json
