version: "2.4"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - 8083:8083
      - 8086:8086
      - 127.0.0.1:25826:25826
    volumes:
      - ./services/influxdb/data:/var/lib/influxdb
      - ./services/influxdb/config:/etc/influxdb
