version: "2.4"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    network_mode: bridge
    restart: always
    environment:
      VIRTUAL_HOST: influxdb.vanhack.ca,influxdb.vanhack.space
      LETSENCRYPT_HOST: influxdb.vanhack.ca,influxdb.vanhack.space
    ports:
      - 8083:8083
      - 8086:8086
      - 127.0.0.1:25826:25826
    volumes:
      - ./services/influxdb/data:/var/lib/influxdb
      - ./services/influxdb/config:/etc/influxdb
